### ISSUE TITLE
Jim-Tcl port of tclpython?

### ISSUE THREAD

**Issue by RobertHenry6bev** [amykyta3/tclpython#8]
Has anybody done any work with this package (or related packages) to make it run under jim-Tcl https://wiki.tcl.tk/13693 which is the Tcl subset used in the openOCD http://openocd.org/ engine?

I have a lot of Python code I want to run from openOCD

**Comment by amykyta3** [comment]
Not aware of any implementations for jim-Tcl. At a glance, jim-Tcl doesn't looks like it would have a C API compatible with full Tcl, so it would likely be a unique implementation of tclpython

**Comment by RobertHenry6bev** [comment]
thank you!
